# state.py
# Defines the shared data structure (GraphState) that flows through
# the entire LangGraph pipeline.
#
# Think of GraphState as a shared whiteboard:
#   - Every node (planner, researcher, critic, synthesizer) can READ the whole state
#   - Every node WRITES only the fields it's responsible for
#   - LangGraph passes the current state into each node and merges the returned updates
#
# Example flow:
#   Planner writes    → angles
#   Researchers write → researcher_outputs (3 parallel writes, all appended)
#   Critic writes     → critique
#   Synthesizer writes→ report

from __future__ import annotations  # allows using type names before they're defined
import operator                      # provides operator.add — used for the list append reducer
from typing import Annotated, TypedDict  # TypedDict = a dict with typed keys; Annotated = attach metadata to a type
from chorus.schemas import AnglePlan, ResearcherOutput, Critique, Report


class GraphState(TypedDict):
    """
    The single source of truth for a Chorus research run.
    All nodes read from and write to this structure.

    LangGraph creates a fresh instance of this for each run,
    so there is no data leakage between different users' runs.
    """

    # The original question submitted by the user.
    # Set once at the start of the run, never changed.
    question: str

    # Unique identifier for this run (UUID generated by POST /run).
    # Used to tag WebSocket events so the frontend knows which run they belong to.
    run_id: str

    # The list of investigative angles produced by the Planner.
    # Each Researcher picks one angle from this list using its angle_index.
    # Starts empty ([]) and is populated by the planner_node.
    angles: list[AnglePlan]

    # The findings from all Researcher agents, collected into one list.
    #
    # Annotated[list[ResearcherOutput], operator.add] is critical here:
    # - The three researchers run IN PARALLEL and each returns a list with one item
    # - Without the reducer, each parallel write would OVERWRITE the previous one
    #   (you'd end up with only 1 output instead of 3)
    # - operator.add tells LangGraph to APPEND the lists instead of replacing
    #   (list + list = combined list, e.g. [A] + [B] + [C] = [A, B, C])
    # DO NOT change this to a plain list[ResearcherOutput] — it would break parallelism.
    researcher_outputs: Annotated[list[ResearcherOutput], operator.add]

    # The Critic agent's assessment of all researcher findings.
    # Starts as None and is populated by critic_node.
    # The Synthesizer cannot run until this is set (enforced by graph edges).
    critique: Critique | None

    # The final structured report produced by the Synthesizer.
    # Starts as None and is populated by synthesizer_node.
    # This is what gets sent to the frontend as the "report.ready" event.
    report: Report | None
